"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Membaca SECRET_KEY dari file .env
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-182^rn+ijw-a&qge-&zx!h$9uh2r(p(95(yamzg!$!2zqp+9m)')

# SECURITY WARNING: don't run with debug turned on in production!
# Praktikum: DEBUG=True diperlukan agar Django Silk dapat merekam query
DEBUG = True  # os.environ.get('DEBUG', 'False') == 'True'

# Mengizinkan akses dari localhost dan container Docker
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', 'silk', 'api',
]

MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',
    'services.rate_limiter.RateLimitMiddleware',  # Redis-based rate limiting
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Auto-detect: gunakan PostgreSQL jika DB_HOST di-set, SQLite untuk dev lokal
if os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD':  os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # Fallback SQLite untuk development lokal tanpa Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Menambahkan STATIC_ROOT yang merupakan best practice untuk production/docker
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

# ============================================================
# Django Silk - Query Profiling Configuration
# ============================================================
SILKY_PYTHON_PROFILER = True          # Aktifkan profiler Python
SILKY_ANALYZE_QUERIES = True          # Analisis query SQL otomatis
SILKY_INTERCEPT_PERCENT = 100         # Record 100% dari semua request
SILKY_MAX_RECORDED_REQUESTS = 10_000  # Simpan hingga 10.000 request

# ============================================================
# JWT Configuration (digunakan oleh api/auth.py)
# ============================================================
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 60   # 1 jam
JWT_REFRESH_TOKEN_EXPIRE_DAYS   = 7    # 7 hari
JWT_ALGORITHM = 'HS256'


# ============================================================
# Redis — Cache Backend
# ============================================================
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'IGNORE_EXCEPTIONS': True,  # Graceful degradation jika Redis down
        },
        'KEY_PREFIX': 'lms',
        'TIMEOUT': 300,  # Default TTL: 5 menit
    }
}

# Rate Limiting (via RateLimitMiddleware)
RATE_LIMIT_REQUESTS = int(os.environ.get('RATE_LIMIT_REQUESTS', 60))  # per menit
RATE_LIMIT_WINDOW   = int(os.environ.get('RATE_LIMIT_WINDOW', 60))    # detik


# ============================================================
# Celery — Async Task Queue
# ============================================================
CELERY_BROKER_URL    = os.environ.get('RABBITMQ_URL', 'amqp://guest:guest@localhost:5672/')
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60        # Hard limit: 30 menit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit: 25 menit


# ============================================================
# MongoDB — Activity Logs & Analytics
# ============================================================
MONGODB_URI = os.environ.get('MONGODB_URI', 'mongodb://localhost:27017/')
MONGODB_DB  = os.environ.get('MONGODB_DB', 'simple_lms_logs')


# ============================================================
# Email Configuration
# ============================================================
EMAIL_BACKEND   = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST      = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT      = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS   = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@simplelms.dev')


# ============================================================
# Reports — lokasi penyimpanan file generated
# ============================================================
REPORTS_DIR = BASE_DIR / 'reports'